Does the state's cost of living in the US relate to the poverty rate of different racial groups, and which states affect certain groups the most?

In [2]:
import os
from dotenv import load_dotenv
import matplotlib.pyplot as plt
import pandas as pd
import requests
import plotly.express as px
from plotly.subplots import make_subplots
# Import all the necessary libraries and modules.

In [3]:
load_dotenv()
API_KEY = os.getenv("CENSUS_API_KEY")
BEA_API_KEY = os.getenv("BEA_API_KEY")
# Looks at the .env file and retrieves the keys to access the API's.

In [4]:
variables = [
    "NAME",          # State name
    "B17001A_001E",  # White Alone population
    "B17001A_002E",  # White Alone population below poverty
    "B17001B_001E",  # Black population
    "B17001B_002E",  # Black population below poverty
    "B17001D_001E",  # Asian population
    "B17001D_002E",  # Asian population below poverty
    "B17001I_001E",  # Hispanic/Latino population
    "B17001I_002E",  # Hispanic/Latino population below poverty
    "B19013_001E",   # Median household income
]
# All the necessary variables from the Census API.

In [5]:
census_url = (f"https://api.census.gov/data/2023/acs/acs1"f"?get={','.join(variables)}&for=state:*&key={API_KEY}")
bea_url = ("https://apps.bea.gov/api/data/"f"?UserID={BEA_API_KEY}""&method=GETDATA""&datasetname=Regional""&TableName=SARPP""&LineCode=1""&GeoFips=STATE""&Year=2023""&ResultFormat=JSON")
# The actual information or location to access to the API's.

In [6]:
census_response = requests.get(census_url)
census_data = census_response.json()
bea_response = requests.get(bea_url)
bea_data = bea_response.json()
# Gets the API's and converts to python data.

In [ ]:
# census_data
# all the information from the variables that are from this census.

[['NAME',
  'B17001A_001E',
  'B17001A_002E',
  'B17001B_001E',
  'B17001B_002E',
  'B17001D_001E',
  'B17001D_002E',
  'B17001I_001E',
  'B17001I_002E',
  'B19013_001E',
  'state'],
 ['Alabama',
  '3221397',
  '358757',
  '1244496',
  '323797',
  '76687',
  '7169',
  '285411',
  '66994',
  '62212',
  '01'],
 ['Alaska',
  '427512',
  '31213',
  None,
  None,
  '42640',
  '5104',
  '53154',
  '6259',
  '86631',
  '02'],
 ['Arizona',
  '4239499',
  '422360',
  '341503',
  '60680',
  '265657',
  '24641',
  '2302507',
  '369016',
  '77315',
  '04'],
 ['Arkansas',
  '2056331',
  '268304',
  '420370',
  '118705',
  '50042',
  '5466',
  '273944',
  '40045',
  '58700',
  '05'],
 ['California',
  '14719922',
  '1450037',
  '2019415',
  '398092',
  '6043524',
  '575339',
  '15507207',
  '2228200',
  '95521',
  '06'],
 ['Colorado',
  '4059535',
  '315966',
  '218530',
  '36186',
  '191419',
  '17892',
  '1307083',
  '177857',
  '92911',
  '08'],
 ['Connecticut',
  '2274537',
  '163394',
  '375327',
  '66261',
  '170906',
  '11800',
  '660291',
  '139641',
  '91665',
  '09'],
 ['Delaware',
  '599340',
  '46033',
  '223525',
  '34127',
  '43814',
  '1890',
  '112613',
  '23130',
  '81361',
  '10'],
 ['District of Columbia',
  '249746',
  '10941',
  '268535',
  '70218',
  None,
  None,
  '79379',
  '4127',
  '108210',
  '11'],
 ['Florida',
  '12284180',
  '1193520',
  '3246435',
  '584758',
  '670302',
  '69921',
  '6109109',
  '918738',
  '73311',
  '12'],
 ['Georgia',
  '5424057',
  '526269',
  '3296550',
  '624350',
  '490546',
  '49710',
  '1198987',
  '213485',
  '74632',
  '13'],
 ['Hawaii',
  '299474',
  '31094',
  None,
  None,
  '519435',
  '36034',
  '139832',
  '18771',
  '95322',
  '15'],
 ['Idaho',
  '1563067',
  '146312',
  '15996',
  '4437',
  None,
  None,
  '265384',
  '37411',
  '74942',
  '16'],
 ['Illinois',
  '7460194',
  '643047',
  '1599146',
  '367486',
  '744168',
  '77468',
  '2341252',
  '328954',
  '80306',
  '17'],
 ['Indiana',
  '5120556',
  '510777',
  '592320',
  '141302',
  '174142',
  '21408',
  '585279',
  '112826',
  '69477',
  '18'],
 ['Iowa',
  '2622259',
  '259610',
  '119920',
  '29172',
  '72205',
  '7644',
  '229519',
  '44788',
  '71433',
  '19'],
 ['Kansas',
  '2169700',
  '208864',
  '145206',
  '27419',
  '75719',
  '10444',
  '392918',
  '65734',
  '70333',
  '20'],
 ['Kentucky',
  '3645630',
  '547878',
  '318741',
  '79493',
  '62268',
  '9529',
  '212471',
  '54809',
  '61118',
  '21'],
 ['Louisiana',
  '2535862',
  '340146',
  '1332297',
  '388288',
  '77939',
  '14547',
  '316538',
  '62390',
  '58229',
  '22'],
 ['Maine',
  '1223787',
  '122117',
  None,
  None,
  None,
  None,
  '28725',
  '3128',
  '73733',
  '23'],
 ['Maryland',
  '2902068',
  '193860',
  '1753666',
  '236177',
  '401648',
  '27509',
  '766959',
  '96213',
  '98678',
  '24'],
 ['Massachusetts',
  '4610745',
  '357835',
  '471084',
  '87124',
  '487520',
  '55942',
  '919205',
  '188995',
  '99858',
  '25'],
 ['Michigan',
  '7274183',
  '799633',
  '1275723',
  '327781',
  '331653',
  '37169',
  '585925',
  '106402',
  '69183',
  '26'],
 ['Minnesota',
  '4313490',
  '322099',
  '399883',
  '90032',
  '292227',
  '24196',
  '358338',
  '50423',
  '85086',
  '27'],
 ['Mississippi',
  '1583463',
  '183412',
  '1009391',
  '278006',
  None,
  None,
  '104022',
  '26214',
  '54203',
  '28'],
 ['Missouri',
  '4699953',
  '481253',
  '636454',
  '137059',
  '123093',
  '15528',
  '316120',
  '47652',
  '68545',
  '29'],
 ['Montana',
  '940412',
  '96738',
  None,
  None,
  None,
  None,
  '50877',
  '9487',
  '70804',
  '30'],
 ['Nebraska',
  '1501726',
  '130048',
  '86032',
  '26154',
  '47232',
  '4374',
  '250454',
  '38895',
  '74590',
  '31'],
 ['Nevada',
  '1573164',
  '153199',
  '289986',
  '55520',
  '290935',
  '27778',
  '946714',
  '132235',
  '76364',
  '32'],
 ['New Hampshire',
  '1195143',
  '82209',
  None,
  None,
  None,
  None,
  '62159',
  '6973',
  '96838',
  '33'],
 ['New Jersey',
  '4882368',
  '342965',
  '1139308',
  '182936',
  '939499',
  '51356',
  '2074575',
  '322189',
  '99781',
  '34'],
 ['New Mexico',
  '986927',
  '131588',
  '40113',
  '9205',
  None,
  None,
  '1007548',
  '208375',
  '62268',
  '35'],
 ['New York',
  '10515840',
  '1088824',
  '2696019',
  '551745',
  '1737620',
  '262143',
  '3784517',
  '798678',
  '82095',
  '36'],
 ['North Carolina',
  '6486788',
  '624562',
  '2115757',
  '411391',
  '350200',
  '35915',
  '1207861',
  '230602',
  '70804',
  '37'],
 ['North Dakota',
  '624039',
  '53716',
  None,
  None,
  None,
  None,
  '36331',
  '5305',
  '76525',
  '38'],
 ['Ohio',
  '8815048',
  '936182',
  '1350443',
  '348429',
  '293261',
  '35736',
  '551545',
  '110104',
  '67769',
  '39'],
 ['Oklahoma',
  '2549285',
  '340625',
  '256631',
  '72033',
  '90335',
  '12151',
  '508731',
  '109146',
  '62138',
  '40'],
 ['Oregon',
  '3075369',
  '349075',
  '83503',
  '20739',
  '191855',
  '17994',
  '619400',
  '100622',
  '80160',
  '41'],
 ['Pennsylvania',
  '9299306',
  '860622',
  '1291805',
  '298275',
  '482640',
  '56968',
  '1114871',
  '249766',
  '73824',
  '42'],
 ['Rhode Island',
  '733846',
  '66517',
  None,
  None,
  None,
  None,
  '192455',
  '33548',
  '84972',
  '44'],
 ['South Carolina',
  '3330660',
  '320994',
  '1268063',
  '291271',
  '92850',
  '8025',
  '385738',
  '84947',
  '67804',
  '45'],
 ['South Dakota',
  '718728',
  '57143',
  None,
  None,
  None,
  None,
  '44432',
  '9517',
  '71810',
  '46'],
 ['Tennessee',
  '5050781',
  '582675',
  '1050385',
  '237423',
  '127513',
  '9819',
  '520805',
  '106840',
  '67631',
  '47'],
 ['Texas',
  '14264710',
  '1441465',
  '3631897',
  '664430',
  '1705526',
  '154626',
  '11934702',
  '2197489',
  '75780',
  '48'],
 ['Utah',
  '2645373',
  '204522',
  '37140',
  '5985',
  '83215',
  '10641',
  '537986',
  '70388',
  '93421',
  '49'],
 ['Vermont',
  '562373',
  '53691',
  None,
  None,
  None,
  None,
  None,
  None,
  '81211',
  '50'],
 ['Virginia',
  '5085320',
  '416712',
  '1534831',
  '257309',
  '594026',
  '39120',
  '942270',
  '116859',
  '89931',
  '51'],
 ['Washington',
  '5012956',
  '454394',
  '303179',
  '51678',
  '769396',
  '59535',
  '1121773',
  '170335',
  '94605',
  '53'],
 ['West Virginia',
  '1551896',
  '245270',
  '47806',
  '14419',
  None,
  None,
  '34840',
  '5557',
  '55948',
  '54'],
 ['Wisconsin',
  '4629517',
  '406442',
  '333062',
  '82376',
  '173929',
  '24283',
  '468850',
  '80343',
  '74631',
  '55'],
 ['Wyoming',
  '481582',
  '51678',
  None,
  None,
  None,
  None,
  '61110',
  '9623',
  '72415',
  '56'],
 ['Puerto Rico',
  '754253',
  '299482',
  '169229',
  '57456',
  None,
  None,
  '3146397',
  '1248150',
  '25621',
  '72']]

In [ ]:
# bea_data 
# # Viewing how to retrieve the data in this BEA API (Different from Census API).

{'BEAAPI': {'Request': {'RequestParam': [{'ParameterName': 'USERID',
     'ParameterValue': '205F15B9-ED92-4B09-8979-284F5E15ABED'},
    {'ParameterName': 'METHOD', 'ParameterValue': 'GETDATA'},
    {'ParameterName': 'DATASETNAME', 'ParameterValue': 'REGIONAL'},
    {'ParameterName': 'TABLENAME', 'ParameterValue': 'SARPP'},
    {'ParameterName': 'LINECODE', 'ParameterValue': '1'},
    {'ParameterName': 'GEOFIPS', 'ParameterValue': 'STATE'},
    {'ParameterName': 'YEAR', 'ParameterValue': '2023'},
    {'ParameterName': 'RESULTFORMAT', 'ParameterValue': 'JSON'}]},
  'Results': {'Statistic': 'RPPs: All items',
   'UnitOfMeasure': 'Index',
   'PublicTable': 'SARPP Regional price parities by state',
   'UTCProductionTime': '2026-09-11T20:42:13.627',
   'NoteRef': ' ',
   'Dimensions': [{'Name': 'Code', 'DataType': 'string', 'IsValue': '0'},
    {'Name': 'GeoFips', 'DataType': 'string', 'IsValue': '0'},
    {'Name': 'GeoName', 'DataType': 'string', 'IsValue': '0'},
    {'Name': 'TimePeriod', 'DataType': 'string', 'IsValue': '0'},
    {'Name': 'DataValue', 'DataType': 'numeric', 'IsValue': '1'},
    {'Name': 'CL_UNIT', 'DataType': 'string', 'IsValue': '0'},
    {'Name': 'UNIT_MULT', 'DataType': 'numeric', 'IsValue': '0'}],
   'Data': [{'Code': 'SARPP-1',
     'GeoFips': '00000',
     'GeoName': 'United States',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '100.000'},
    {'Code': 'SARPP-1',
     'GeoFips': '01000',
     'GeoName': 'Alabama',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '89.097'},
    {'Code': 'SARPP-1',
     'GeoFips': '02000',
     'GeoName': 'Alaska',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '103.297'},
    {'Code': 'SARPP-1',
     'GeoFips': '04000',
     'GeoName': 'Arizona',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '100.742'},
    {'Code': 'SARPP-1',
     'GeoFips': '05000',
     'GeoName': 'Arkansas',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '86.810'},
    {'Code': 'SARPP-1',
     'GeoFips': '06000',
     'GeoName': 'California',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '112.195'},
    {'Code': 'SARPP-1',
     'GeoFips': '08000',
     'GeoName': 'Colorado',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '101.856'},
    {'Code': 'SARPP-1',
     'GeoFips': '09000',
     'GeoName': 'Connecticut',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '104.201'},
    {'Code': 'SARPP-1',
     'GeoFips': '10000',
     'GeoName': 'Delaware',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '98.759'},
    {'Code': 'SARPP-1',
     'GeoFips': '11000',
     'GeoName': 'District of Columbia',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '110.713'},
    {'Code': 'SARPP-1',
     'GeoFips': '12000',
     'GeoName': 'Florida',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '103.636'},
    {'Code': 'SARPP-1',
     'GeoFips': '13000',
     'GeoName': 'Georgia',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '96.494'},
    {'Code': 'SARPP-1',
     'GeoFips': '15000',
     'GeoName': 'Hawaii',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '109.703'},
    {'Code': 'SARPP-1',
     'GeoFips': '16000',
     'GeoName': 'Idaho',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '92.236'},
    {'Code': 'SARPP-1',
     'GeoFips': '17000',
     'GeoName': 'Illinois',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '98.752'},
    {'Code': 'SARPP-1',
     'GeoFips': '18000',
     'GeoName': 'Indiana',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '92.097'},
    {'Code': 'SARPP-1',
     'GeoFips': '19000',
     'GeoName': 'Iowa',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '88.769'},
    {'Code': 'SARPP-1',
     'GeoFips': '20000',
     'GeoName': 'Kansas',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '89.908'},
    {'Code': 'SARPP-1',
     'GeoFips': '21000',
     'GeoName': 'Kentucky',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '89.890'},
    {'Code': 'SARPP-1',
     'GeoFips': '22000',
     'GeoName': 'Louisiana',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '88.700'},
    {'Code': 'SARPP-1',
     'GeoFips': '23000',
     'GeoName': 'Maine',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '97.964'},
    {'Code': 'SARPP-1',
     'GeoFips': '24000',
     'GeoName': 'Maryland',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '104.602'},
    {'Code': 'SARPP-1',
     'GeoFips': '25000',
     'GeoName': 'Massachusetts',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '107.675'},
    {'Code': 'SARPP-1',
     'GeoFips': '26000',
     'GeoName': 'Michigan',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '94.296'},
    {'Code': 'SARPP-1',
     'GeoFips': '27000',
     'GeoName': 'Minnesota',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '98.302'},
    {'Code': 'SARPP-1',
     'GeoFips': '28000',
     'GeoName': 'Mississippi',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '86.792'},
    {'Code': 'SARPP-1',
     'GeoFips': '29000',
     'GeoName': 'Missouri',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '91.104'},
    {'Code': 'SARPP-1',
     'GeoFips': '30000',
     'GeoName': 'Montana',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '91.014'},
    {'Code': 'SARPP-1',
     'GeoFips': '31000',
     'GeoName': 'Nebraska',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '90.288'},
    {'Code': 'SARPP-1',
     'GeoFips': '32000',
     'GeoName': 'Nevada',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '97.861'},
    {'Code': 'SARPP-1',
     'GeoFips': '33000',
     'GeoName': 'New Hampshire',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '105.393'},
    {'Code': 'SARPP-1',
     'GeoFips': '34000',
     'GeoName': 'New Jersey',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '108.941'},
    {'Code': 'SARPP-1',
     'GeoFips': '35000',
     'GeoName': 'New Mexico',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '90.981'},
    {'Code': 'SARPP-1',
     'GeoFips': '36000',
     'GeoName': 'New York',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '107.842'},
    {'Code': 'SARPP-1',
     'GeoFips': '37000',
     'GeoName': 'North Carolina',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '94.399'},
    {'Code': 'SARPP-1',
     'GeoFips': '38000',
     'GeoName': 'North Dakota',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '88.174'},
    {'Code': 'SARPP-1',
     'GeoFips': '39000',
     'GeoName': 'Ohio',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '91.903'},
    {'Code': 'SARPP-1',
     'GeoFips': '40000',
     'GeoName': 'Oklahoma',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '88.680'},
    {'Code': 'SARPP-1',
     'GeoFips': '41000',
     'GeoName': 'Oregon',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '104.812'},
    {'Code': 'SARPP-1',
     'GeoFips': '42000',
     'GeoName': 'Pennsylvania',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '97.400'},
    {'Code': 'SARPP-1',
     'GeoFips': '44000',
     'GeoName': 'Rhode Island',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '102.065'},
    {'Code': 'SARPP-1',
     'GeoFips': '45000',
     'GeoName': 'South Carolina',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '93.477'},
    {'Code': 'SARPP-1',
     'GeoFips': '46000',
     'GeoName': 'South Dakota',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '88.149'},
    {'Code': 'SARPP-1',
     'GeoFips': '47000',
     'GeoName': 'Tennessee',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '92.094'},
    {'Code': 'SARPP-1',
     'GeoFips': '48000',
     'GeoName': 'Texas',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '97.140'},
    {'Code': 'SARPP-1',
     'GeoFips': '49000',
     'GeoName': 'Utah',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '95.716'},
    {'Code': 'SARPP-1',
     'GeoFips': '50000',
     'GeoName': 'Vermont',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '97.142'},
    {'Code': 'SARPP-1',
     'GeoFips': '51000',
     'GeoName': 'Virginia',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '101.331'},
    {'Code': 'SARPP-1',
     'GeoFips': '53000',
     'GeoName': 'Washington',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '108.370'},
    {'Code': 'SARPP-1',
     'GeoFips': '54000',
     'GeoName': 'West Virginia',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '89.633'},
    {'Code': 'SARPP-1',
     'GeoFips': '55000',
     'GeoName': 'Wisconsin',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '93.220'},
    {'Code': 'SARPP-1',
     'GeoFips': '56000',
     'GeoName': 'Wyoming',
     'TimePeriod': '2023',
     'CL_UNIT': 'Index',
     'UNIT_MULT': '0',
     'DataValue': '91.551'}],
   'Notes': [{'NoteRef': ' ',
     'NoteText': 'Last updated: February 19, 2026-- new statistics for 2024; revised statistics for 2008-2023.'}]}}}

In [9]:
df = pd.DataFrame(census_data[1:], columns=census_data[0])
df.head()
# Simple retrieve from the first column and then on. 
# Shows the first five top rows.

,NAME,B17001A_001E,B17001A_002E,B17001B_001E,B17001B_002E,B17001D_001E,B17001D_002E,B17001I_001E,B17001I_002E,B19013_001E,state
0,Alabama,3221397,358757,1244496,323797,76687,7169,285411,66994,62212,01
1,Alaska,427512,31213,None,None,42640,5104,53154,6259,86631,02
2,Arizona,4239499,422360,341503,60680,265657,24641,2302507,369016,77315,04
3,Arkansas,2056331,268304,420370,118705,50042,5466,273944,40045,58700,05
4,California,14719922,1450037,2019415,398092,6043524,575339,15507207,2228200,95521,06

In [10]:
bea_results = bea_data["BEAAPI"]["Results"]["Data"]
bea_df = pd.DataFrame(bea_results)
bea_df.head()
# Digging through the layers to get to the data.

      Code GeoFips        GeoName TimePeriod CL_UNIT UNIT_MULT DataValue
0  SARPP-1   00000  United States       2023   Index         0   100.000
1  SARPP-1   01000        Alabama       2023   Index         0    89.097
2  SARPP-1   02000         Alaska       2023   Index         0   103.297
3  SARPP-1   04000        Arizona       2023   Index         0   100.742
4  SARPP-1   05000       Arkansas       2023   Index         0    86.810

In [11]:
bea_df = bea_df[["GeoName", "DataValue"]] # Getting specific columns that will be used in the research analysis.

In [12]:
bea_df = bea_df.rename(columns = {"GeoName": "NAME", "DataValue": "RPP"}) 
# Need to change the "GeoName" to match "NAME", to allow a merge later with the other table (Census API). 
# Also Chaning DataValue to RPP (Regional Price Parities), the mesure of cost of living for this analysis. Purchasing power by understanding how much the price of goods and services change.

In [13]:
bea_df.head() # Shows the first five rows.

            NAME      RPP
0  United States  100.000
1        Alabama   89.097
2         Alaska  103.297
3        Arizona  100.742
4       Arkansas   86.810

In [14]:
df = df.merge(bea_df, on = "NAME", how = "left") # Merges the two tables togther based on the same column "NAME"

In [15]:
df[["NAME", "RPP"]].head(10) # Shows the first 10 rows of the information after merging or joining the two tables.

                   NAME      RPP
0               Alabama   89.097
1                Alaska  103.297
2               Arizona  100.742
3              Arkansas   86.810
4            California  112.195
5              Colorado  101.856
6           Connecticut  104.201
7              Delaware   98.759
8  District of Columbia  110.713
9               Florida  103.636

In [16]:
num_com = df.columns[1:]
df[num_com] = df[num_com].apply(pd.to_numeric, errors = "coerce")
df = df.rename(columns = {
    "B17001A_002E": "White_poverty_population",
    "B17001B_002E": "Black_poverty_population",
    "B17001D_002E": "Asian_poverty_population",
    "B17001I_002E": "Hispanic_poverty_population",
    "B19013_001E": "Median Household Income"
})
# Converts data in the table that are string but look like numbers into int or float and if there is a null or N/A answer NAN.
# Changes variable names into readable names

In [17]:
df["White Poverty Rate"] = (df["White_poverty_population"] / df["B17001A_001E"] * 100).round(1)
df["Black Poverty Rate"] = (df["Black_poverty_population"] / df["B17001B_001E"] * 100).round(1)
df["Asian Poverty Rate"] = (df["Asian_poverty_population"] / df["B17001D_001E"] * 100).round(1)
df["Hispanic Poverty Rate"] = (df["Hispanic_poverty_population"] / df["B17001I_001E"] * 100).round(1)
# Finds the precentage rate of poverty for each racial group by dividing the total amount below poverty by the total amount.
# As well round to the tenth decimal number.

In [18]:
state = {
    1: "AL",
    2: "AK",
    4: "AZ",
    5: "AR",
    6: "CA",
    8: "CO",
    9: "CT",
    10: "DE",
    11: "DC",
    12: "FL",
    13: "GA",
    15: "HI",
    16: "ID",
    17: "IL",
    18: "IN",
    19: "IA",
    20: "KS",
    21: "KY",
    22: "LA",
    23: "ME",
    24: "MD",
    25: "MA",
    26: "MI",
    27: "MN",
    28: "MS",
    29: "MO",
    30: "MT",
    31: "NE",
    32: "NV",
    33: "NH",
    34: "NJ",
    35: "NM",
    36: "NY",
    37: "NC",
    38: "ND",
    39: "OH",
    40: "OK",
    41: "OR",
    42: "PA",
    44: "RI",
    45: "SC",
    46: "SD",
    47: "TN",
    48: "TX",
    49: "UT",
    50: "VT",
    51: "VA",
    53: "WA",
    54: "WV",
    55: "WI",
    56: "WY"
}

df["State"] = df["state"].map(state)

In [19]:
figRPP = px.choropleth(df, locations = "State", locationmode = "USA-states", color_continuous_scale = "Blues", color = "RPP", scope = "usa", title = "The RPP rate for each State", height = 900, width = 1700)
figRPP.show()

fig1 = px.choropleth(df, locations = "State", locationmode = "USA-states", color = "Black Poverty Rate")

fig2 = px.choropleth(df, locations = "State", locationmode = "USA-states", color = "White Poverty Rate")

fig3 = px.choropleth(df,locations = "State", locationmode = "USA-states", color = "Asian Poverty Rate")

fig4 = px.choropleth(df, locations = "State", locationmode = "USA-states", color = "Hispanic Poverty Rate")

figFRS = make_subplots(rows = 2, cols = 2,
    specs = [[{"type": "choropleth"}, {"type": "choropleth"}], [{"type": "choropleth"}, {"type": "choropleth"}]],
    subplot_titles = ["Black Poverty Rate by State", "White Poverty Rate by State", "Asian Poverty Rate by State", "Hispanic Poverty Rate by State"])
# Poverty Rate graphs
figFRS.add_trace(fig1.data[0], row = 1, col = 1)
figFRS.add_trace(fig2.data[0], row = 1, col = 2)
figFRS.add_trace(fig3.data[0], row = 2, col = 1)
figFRS.add_trace(fig4.data[0], row = 2, col = 2)

figFRS.update_geos(scope="usa")
figFRS.update_layout(height = 900, width = 1700)

figFRS.show()
# Creates an interactive graphs with hovering text as well shows the distribution/spread of poverty rates for each racial group for each state.
# Creates an interactive graphs with hovering text as well shows the RPP for each state.

In [20]:
fig1 = px.choropleth(df, locations = "State", locationmode = "USA-states", color = "Black_poverty_population")

fig2 = px.choropleth(df, locations = "State", locationmode = "USA-states", color = "White_poverty_population")

fig3 = px.choropleth(df, locations = "State", locationmode = "USA-states", color = "Asian_poverty_population")

fig4 = px.choropleth(df, locations = "State", locationmode = "USA-states", color = "Hispanic_poverty_population")
figFPS = make_subplots(rows = 2, cols = 2,
    specs = [[{"type": "choropleth"}, {"type": "choropleth"}], [{"type": "choropleth"}, {"type": "choropleth"}]],
    subplot_titles = ["Black Poverty Population For Each State", "White Poverty Population For Each State", "Asian Poverty Population For Each State", "Hispanic Poverty Population For Each State"]
)
figFPS.add_trace(fig1.data[0], row = 1, col = 1)
figFPS.add_trace(fig2.data[0], row = 1, col = 2)
figFPS.add_trace(fig3.data[0], row = 2, col = 1)
figFPS.add_trace(fig4.data[0], row = 2, col = 2)

figFPS.update_geos(scope = "usa")
figFPS.update_layout(height = 900, width = 1700)

figFPS.show()
# Creates a map for racials groups and shows the distribution of poverty population in the US.

In [21]:
fig1 = px.scatter(df, x = "Black_poverty_population", y = "Black Poverty Rate")

fig2 = px.scatter(df, x = "White_poverty_population", y = "White Poverty Rate")

fig3 = px.scatter(df, x = "Asian_poverty_population", y = "Asian Poverty Rate")

fig4 = px.scatter(df, x = "Hispanic_poverty_population", y = "Hispanic Poverty Rate")
figFPR = make_subplots(rows = 2, cols = 2,
    specs = [[{"type": "scatter"}, {"type": "scatter"}], [{"type": "scatter"}, {"type": "scatter"}]],
    subplot_titles = ["Black Poverty Population vs Poverty Rate", "White Poverty Population vs Poverty Rate", "Asian Poverty Population vs Poverty Rate", "Hispanic Poverty Population vs Poverty Rate"])

figFPR.add_trace(fig1.data[0], row = 1, col = 1)
figFPR.add_trace(fig2.data[0], row = 1, col = 2)
figFPR.add_trace(fig3.data[0], row = 2, col = 1)
figFPR.add_trace(fig4.data[0], row = 2, col = 2)

figFPR.update_layout(width = 1700, height = 900)

figFPR.show()

# Creates a scatter plot showing the relationship of rate and population for poverty with different racial groups.

In [22]:
df["Highest Poverty population"] = df[["White_poverty_population", "Black_poverty_population", "Asian_poverty_population", "Hispanic_poverty_population"]].max(axis = 1)
df["Highest Poverty POP"] = df[["White_poverty_population", "Black_poverty_population", "Asian_poverty_population", "Hispanic_poverty_population"]].idxmax(axis = 1)

df["Highest Poverty Rate"] = df[["White Poverty Rate", "Black Poverty Rate", "Asian Poverty Rate", "Hispanic Poverty Rate"]].max(axis = 1)
df["Highest Poverty Group"] = df[["White Poverty Rate", "Black Poverty Rate", "Asian Poverty Rate", "Hispanic Poverty Rate"]].idxmax(axis = 1)

# Find the highest number comparing to each column by the first row and check agaisnt each other.
# Retrieve the column name in which this information was found.
# Poverty rate and Poverty Population.

In [23]:
GRC = {
    "White Poverty Rate": "#30C646",
    "Black Poverty Rate": "#C63E40",
    "Asian Poverty Rate": "#783BBF",
    "Hispanic Poverty Rate": "#C7C236"
}
figRHR = px.scatter(df, x = "RPP", y = "Highest Poverty Rate", color = "Highest Poverty Group", color_discrete_map = GRC, hover_name = "NAME", title = "RPP vs. Highest Poverty Rate", height = 500, width = 1715)
figRHR.show()
# Creates an interactive scatter plot that shows the relation between poverty rate and RPP (the highest poverty rate in each state)

In [24]:
GRC = {
    "White_poverty_population": "#30C646",
    "Black_poverty_population": "#C63E40",
    "Asian_poverty_population": "#783BBF",
    "Hispanic_poverty_population": "#C7C236"
}
figRHP = px.scatter(df, x = "RPP", y = "Highest Poverty population", color = "Highest Poverty POP", color_discrete_map = GRC, hover_name = "NAME", title = "RPP vs. Highest Poverty POP", height = 500, width = 1715)
figRHP.show()
# Creates an interactive scatter plot that shows the relation between poverty population and RPP (the highest poverty pop in each state)

In [ ]:
GRC = {
    "White Poverty Rate": "#30C646",
    "Black Poverty Rate": "#C63E40",
    "Asian Poverty Rate": "#783BBF",
    "Hispanic Poverty Rate": "#C7C236"
}
figRPH = px.scatter(df, x = "Median Household Income", y = "RPP", color = "Highest Poverty Group", color_discrete_map = GRC, hover_name = "NAME", title = "RPP vs. Median household", height = 500, width = 1715)
figRPH.show()
# Creates an interactive scatter plot that showcases the relationship of RPP and median household income as well which racial group has the highest poverty.

In [26]:
GRC = {
    "White Poverty Rate": "#30C646",
    "Black Poverty Rate": "#C63E40",
    "Asian Poverty Rate": "#783BBF",
    "Hispanic Poverty Rate": "#C7C236"
}
figAHP = px.choropleth(df, locations = "State", locationmode = "USA-states", color = "Highest Poverty Group", color_discrete_map = GRC, scope = "usa", title = "Each State With The Highest Racial Poverty Rate", 
height = 900, width = 1700, 
hover_data = {
        "State": True,
        "Highest Poverty Group": True,
        "Highest Poverty Rate": True,
        "Highest Poverty POP": True,
        "Median Household Income": True
    })
figAHP.show()
# Creates an interactive map that shows the highest poverty rate in each state